<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Max Ghenis">
<meta name="dcterms.date" content="2026-08-16">

<title>Administrative quality control data as an oracle: verifying encoded SNAP rules and simulating payment error under cost sharing</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8ffd5f67044e5306d9846f29df41dda5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Administrative quality control data as an oracle: verifying encoded SNAP rules and simulating payment error under cost sharing">
<meta name="citation_abstract" content="Beginning in fiscal year 2028, each state&amp;amp;#039;s Supplemental Nutrition
Assistance Program (SNAP) payment error rate sets its share of benefit
costs, in steps of five percentage points at rates of 6, 8, and 10
percent. A measurement system built for oversight now moves large sums,
which raises two questions this paper treats together: whether the rules
that produce benefit amounts can be executed correctly, and how the
errors that remain should be measured and simulated. I use the USDA
Quality Control (QC) public-use files as a verification oracle for
independently encoded SNAP rules: across seven states, the encodings
reproduce the file's benefit-computation chain, from file-recorded
intermediates, exactly — all 6,081 in-scope cases of the 6,194-case
official universe (113 documented exclusions), six computation stages
per case, zero dollar tolerance — a process that surfaced and fixed two
defects in the encodings and surfaced errata in the federal technical
documentation. Replaying reconstructed pre-edit case facts through the
verified engine explains 78.4% of Colorado's above-threshold official
error cases — and 91.4% of sub-threshold deviations — as correct
arithmetic on wrong facts. Pricing that decomposition through the
formula's tiers, elections, and delay clause — removing the error
dollars the file's cause codes assign to the computing apparatus, an
accounting scenario rather than a causal estimate — moves summed
expected fiscal 2028 bills from $7.7B to $7.6B a year under a strict
class convention and $6.9B under a broad one, and not monotonically:
a state just under the statute's delay threshold sees its near-term
expected bill rise as its measured rate
falls. I also fit and validate a distributional
model of case-level payment deviations, reporting its validation
failures alongside its results, and serve one policy counterfactual
from it in the deployed simulator: a standard medical deduction
scenario computed on engine-recomputed case parameters, whose
model-implied Colorado effect opposes the naive accounting bound in
sign. The central finding, from an open Monte
Carlo simulator resampling each state's own QC cases, is about
measurement: at regulatory sample sizes, several states face nearly
even odds — 46 to 50 percent — of being assigned a different cost tier
than their official point rate implies. The fiscal 2025 rates,
published in June 2026, land where that mechanism says realized years
should: 18 of 53 jurisdictions changed cost-sharing tiers in one
year, and only seven of those changes exceed the 95% band that two
years of sampling noise — estimated from fiscal 2024 microdata alone
— implies.
">
<meta name="citation_author" content="Max Ghenis">
<meta name="citation_publication_date" content="2026-08-16">
<meta name="citation_cover_date" content="2026-08-16">
<meta name="citation_year" content="2026">
<meta name="citation_online_date" content="2026-08-16">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Technical documentation for the fiscal year 2024 supplemental nutrition assistance program quality control database and the QC minimodel;,citation_author=U.S. Department of Agriculture, Food and Nutrition Service;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://snapqcdata.net/datafiles;">
<meta name="citation_reference" content="citation_title=Supplemental nutrition assistance program payment error rates, fiscal year 2024;,citation_author=U.S. Department of Agriculture, Food and Nutrition Service;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.fns.usda.gov/snap/qc/per;">
<meta name="citation_reference" content="citation_title=Snap_qc: Reconstruction and analysis code for the SNAP quality control public-use files;,citation_author=Eric Giannella;,citation_author=Ben Molin;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://github.com/giannella/snap_qc;">
<meta name="citation_reference" content="citation_title=Smearing estimate: A nonparametric retransformation method;,citation_author=Naihua Duan;,citation_publication_date=1983;,citation_cover_date=1983;,citation_year=1983;,citation_fulltext_html_url=https://doi.org/10.1080/01621459.1983.10478017;,citation_issue=383;,citation_volume=78;,citation_journal_title=Journal of the American Statistical Association;">
<meta name="citation_reference" content="citation_title=Regression quantiles;,citation_author=Roger Koenker;,citation_author=Gilbert Bassett;,citation_publication_date=1978;,citation_cover_date=1978;,citation_year=1978;,citation_fulltext_html_url=https://doi.org/10.2307/1913643;,citation_issue=1;,citation_volume=46;,citation_journal_title=Econometrica;">
<meta name="citation_reference" content="citation_title=Bootstrap methods: Another look at the jackknife;,citation_author=Bradley Efron;,citation_publication_date=1979;,citation_cover_date=1979;,citation_year=1979;,citation_fulltext_html_url=https://doi.org/10.1214/aos/1176344552;,citation_issue=1;,citation_volume=7;,citation_journal_title=The Annals of Statistics;">
<meta name="citation_reference" content="citation_title=Scikit-learn: Machine learning in Python;,citation_author=Fabian Pedregosa;,citation_author=Gaël Varoquaux;,citation_author=Alexandre Gramfort;,citation_author=Vincent Michel;,citation_author=Bertrand Thirion;,citation_author=Olivier Grisel;,citation_author=Mathieu Blondel;,citation_author=Peter Prettenhofer;,citation_author=Ron Weiss;,citation_author=Vincent Dubourg;,citation_author=Jake Vanderplas;,citation_author=Alexandre Passos;,citation_author=David Cournapeau;,citation_author=Matthieu Brucher;,citation_author=Matthieu Perrot;,citation_author=Édouard Duchesnay;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_fulltext_html_url=https://jmlr.org/papers/v12/pedregosa11a.html;,citation_volume=12;,citation_journal_title=Journal of Machine Learning Research;">
<meta name="citation_reference" content="citation_title=Catala: A programming language for the law;,citation_author=Denis Mérigoux;,citation_author=Nicolas Chataing;,citation_author=Jonathan Protzenko;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://doi.org/10.1145/3473582;,citation_issue=ICFP;,citation_volume=5;,citation_journal_title=Proceedings of the ACM on Programming Languages;">
<meta name="citation_reference" content="citation_title=Cracking the code: Rulemaking for humans and machines;,citation_author=James Mohun;,citation_author=Alex Roberts;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=https://doi.org/10.1787/3afe6ba5-en;,citation_technical_report_institution=OECD Observatory of Public Sector Innovation;,citation_technical_report_number=42;">
<meta name="citation_reference" content="citation_title=A modern compiler for the French tax code;,citation_author=Denis Mérigoux;,citation_author=Raphaël Monat;,citation_author=Jonathan Protzenko;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://doi.org/10.1145/3446804.3446850;,citation_conference_title=Proceedings of the 30th ACM SIGPLAN international conference on compiler construction (CC ’21);">
<meta name="citation_reference" content="citation_title=Quantile and probability curves without crossing;,citation_author=Victor Chernozhukov;,citation_author=Iván Fernández-Val;,citation_author=Alfred Galichon;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_fulltext_html_url=https://doi.org/10.3982/ECTA7880;,citation_issue=3;,citation_volume=78;,citation_journal_title=Econometrica;">
<meta name="citation_reference" content="citation_title=The promise and pitfalls of using imprecise school accountability measures;,citation_author=Thomas J. Kane;,citation_author=Douglas O. Staiger;,citation_publication_date=2002;,citation_cover_date=2002;,citation_year=2002;,citation_fulltext_html_url=https://doi.org/10.1257/089533002320950993;,citation_issue=4;,citation_volume=16;,citation_journal_title=Journal of Economic Perspectives;">
<meta name="citation_reference" content="citation_title=Administrative burden: Policymaking by other means;,citation_author=Pamela Herd;,citation_author=Donald P. Moynihan;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;">
<meta name="citation_reference" content="citation_title=Errors and fraud in the supplemental nutrition assistance program (SNAP);,citation_author=Congressional Research Service;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://www.congress.gov/crs-product/IF10860;">
<meta name="citation_reference" content="citation_title=FNS handbook 310: SNAP quality control review handbook;,citation_author=U.S. Department of Agriculture, Food and Nutrition Service;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_fulltext_html_url=https://www.fns.usda.gov/snap/fns-handbook-310;">
<meta name="citation_reference" content="citation_title=False claims act settlements concerning bias in SNAP quality control processes (virginia, wisconsin, alaska, texas, louisiana, mississippi, florida, tennessee), cumulative recoveries exceeding $67 million;,citation_author=U.S. Department of Justice;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://www.justice.gov/archives/opa/pr/tennessee-department-human-services-agrees-pay-68-million-resolve-false-claims-act-liability;">
<meta name="citation_reference" content="citation_title=Errors and fraud in the supplemental nutrition assistance program (SNAP);,citation_author=Congressional Research Service;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_fulltext_html_url=https://www.congress.gov/crs_external_products/R/PDF/R45147/R45147.4.pdf;">
<meta name="citation_reference" content="citation_title=Supplemental nutrition assistance program payment error rates, fiscal year 2025;,citation_author=U.S. Department of Agriculture, Food and Nutrition Administration;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://www.fns.usda.gov/snap/qc/per;">
<meta name="citation_reference" content="citation_title=Rethinking quality control: A new system for the Food Stamp Program;,citation_author=National Research Council;,citation_publication_date=1987;,citation_cover_date=1987;,citation_year=1987;,citation_fulltext_html_url=https://nap.nationalacademies.org/catalog/18900/;,citation_technical_report_institution=National Academies Press;">
<meta name="citation_reference" content="citation_title=Federal and state liability for inaccurate payments of Food Stamp, AFDC, and SSI program benefits;,citation_author=U.S. General Accounting Office;,citation_publication_date=1984;,citation_cover_date=1984;,citation_year=1984;,citation_fulltext_html_url=https://gao.justia.com/social-security-administration/1984/4/federal-and-state-liability-for-inaccurate-payments-of-food-stamp-afdc-and-ssi-program-benefits-rced-84-155;,citation_technical_report_institution=U.S. General Accounting Office;,citation_technical_report_number=RCED-84-155;">
<meta name="citation_reference" content="citation_title=Predicting experimental results: Who knows what?;,citation_author=Stefano DellaVigna;,citation_author=Devin Pope;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_issue=6;,citation_volume=126;,citation_journal_title=Journal of Political Economy;">
<meta name="citation_reference" content="citation_title=Program recertification costs: Evidence from SNAP;,citation_author=Tatiana Homonoff;,citation_author=Jason Somerville;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_issue=4;,citation_volume=13;,citation_journal_title=American Economic Journal: Economic Policy;">
<meta name="citation_reference" content="citation_title=Using synthetic controls: Feasibility, data requirements, and methodological aspects;,citation_author=Alberto Abadie;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_issue=2;,citation_volume=59;,citation_journal_title=Journal of Economic Literature;">
<meta name="citation_reference" content="citation_title=Synthetic control methods for comparative case studies: Estimating the effect of California’s tobacco control program;,citation_author=Alberto Abadie;,citation_author=Alexis Diamond;,citation_author=Jens Hainmueller;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_issue=490;,citation_volume=105;,citation_journal_title=Journal of the American Statistical Association;">
<meta name="citation_reference" content="citation_title=Texas Health and Human Services Commission agrees to pay over $15 million to resolve False Claims Act liability for deficient SNAP quality control;,citation_author=U.S. Department of Justice;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_fulltext_html_url=https://www.justice.gov/opa/pr/texas-health-and-human-services-commission-agrees-pay-over-15-million-resolve-false-claims;">
<meta name="citation_reference" content="citation_title=Forecasting the results of experiments: Piloting an elicitation strategy;,citation_author=Stefano DellaVigna;,citation_author=Nicholas Otis;,citation_author=Eva Vivalt;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_doi=10.1257/pandp.20201080;,citation_volume=110;,citation_journal_title=AEA Papers and Proceedings;">
<meta name="citation_reference" content="citation_title=Food Stamp Program: Payment errors and trafficking have declined despite increased program participation;,citation_author=U.S. Government Accountability Office;,citation_publication_date=2007;,citation_cover_date=2007;,citation_year=2007;,citation_fulltext_html_url=https://www.gao.gov/products/gao-07-422t;,citation_technical_report_institution=U.S. Government Accountability Office;,citation_technical_report_number=GAO-07-422T;">
<meta name="citation_reference" content="citation_title=What a system replacement does to measured error: Three SNAP eligibility-system migrations in the quality-control record;,citation_author=Max Ghenis;,citation_publication_date=2026;,citation_cover_date=2026;,citation_year=2026;,citation_fulltext_html_url=https://policyengine.org/us/snap-payment-error-simulator/paper-migrations;">
</head>

<body class="quarto-light">

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Administrative quality control data as an oracle: verifying encoded SNAP rules and simulating payment error under cost sharing</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Author</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Max Ghenis <a href="mailto:max@policyengine.org" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        PolicyEngine
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
                <div>
            <div class="quarto-title-meta-heading">Published</div>
            <div class="quarto-title-meta-contents">
              <p class="date">August 16, 2026</p>
            </div>
          </div>
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></p></div></div></div>
    </div>

    <div>
      <div class="abstract">
        <div class="block-title">Abstract</div>
        <p>Beginning in fiscal year 2028, each state’s Supplemental Nutrition Assistance Program (SNAP) payment error rate sets its share of benefit costs, in steps of five percentage points at rates of 6, 8, and 10 percent. A measurement system built for oversight now moves large sums, which raises two questions this paper treats together: whether the rules that produce benefit amounts can be executed correctly, and how the errors that remain should be measured and simulated. I use the USDA Quality Control (QC) public-use files as a verification oracle for independently encoded SNAP rules: across seven states, the encodings reproduce the file’s benefit-computation chain, from file-recorded intermediates, exactly — all 6,081 in-scope cases of the 6,194-case official universe (113 documented exclusions), six computation stages per case, zero dollar tolerance — a process that surfaced and fixed two defects in the encodings and surfaced errata in the federal technical documentation. Replaying reconstructed pre-edit case facts through the verified engine explains 78.4% of Colorado’s above-threshold official error cases — and 91.4% of sub-threshold deviations — as correct arithmetic on wrong facts. Pricing that decomposition through the formula’s tiers, elections, and delay clause — removing the error dollars the file’s cause codes assign to the computing apparatus, an accounting scenario rather than a causal estimate — moves summed expected fiscal 2028 bills from $7.7B to $7.6B a year under a strict class convention and $6.9B under a broad one, and not monotonically: a state just under the statute’s delay threshold sees its near-term expected bill rise as its measured rate falls. I also fit and validate a distributional model of case-level payment deviations, reporting its validation failures alongside its results, and serve one policy counterfactual from it in the deployed simulator: a standard medical deduction scenario computed on engine-recomputed case parameters, whose model-implied Colorado effect opposes the naive accounting bound in sign. The central finding, from an open Monte Carlo simulator resampling each state’s own QC cases, is about measurement: at regulatory sample sizes, several states face nearly even odds — 46 to 50 percent — of being assigned a different cost tier than their official point rate implies. The fiscal 2025 rates, published in June 2026, land where that mechanism says realized years should: 18 of 53 jurisdictions changed cost-sharing tiers in one year, and only seven of those changes exceed the 95% band that two years of sampling noise — estimated from fiscal 2024 microdata alone — implies.</p>
      </div>
    </div>


    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#sec-related" id="toc-sec-related" class="nav-link" data-scroll-target="#sec-related">Related work</a></li>
  <li><a href="#sec-qc" id="toc-sec-qc" class="nav-link" data-scroll-target="#sec-qc">The QC system and the money attached to it</a></li>
  <li><a href="#sec-oracle" id="toc-sec-oracle" class="nav-link" data-scroll-target="#sec-oracle">The QC file as a verification oracle</a>
  <ul class="collapse">
  <li><a href="#sec-oracle-scope" id="toc-sec-oracle-scope" class="nav-link" data-scroll-target="#sec-oracle-scope">What the parity target is</a></li>
  </ul></li>
  <li><a href="#sec-decompose" id="toc-sec-decompose" class="nav-link" data-scroll-target="#sec-decompose">Decomposing measured error: computation versus facts</a></li>
  <li><a href="#sec-model" id="toc-sec-model" class="nav-link" data-scroll-target="#sec-model">Modeling the error process</a></li>
  <li><a href="#sec-simulate" id="toc-sec-simulate" class="nav-link" data-scroll-target="#sec-simulate">Simulating measured rates under cost sharing</a>
  <ul class="collapse">
  <li><a href="#sec-fy2025" id="toc-sec-fy2025" class="nav-link" data-scroll-target="#sec-fy2025">The realized fiscal 2025 rates</a></li>
  <li><a href="#sec-adoption" id="toc-sec-adoption" class="nav-link" data-scroll-target="#sec-adoption">Pricing engine adoption through the formula</a></li>
  <li><a href="#sec-fy2027" id="toc-sec-fy2027" class="nav-link" data-scroll-target="#sec-fy2027">The fiscal 2027 measurement year</a></li>
  <li><a href="#sec-events" id="toc-sec-events" class="nav-link" data-scroll-target="#sec-events">System replacements in the record: event studies</a></li>
  </ul></li>
  <li><a href="#sec-roadmap" id="toc-sec-roadmap" class="nav-link" data-scroll-target="#sec-roadmap">Toward engine-computed counterfactuals</a></li>
  <li><a href="#sec-limitations" id="toc-sec-limitations" class="nav-link" data-scroll-target="#sec-limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#sec-availability" id="toc-sec-availability" class="nav-link" data-scroll-target="#sec-availability">Data and code availability</a></li>
  <li><a href="#disclosure" id="toc-disclosure" class="nav-link" data-scroll-target="#disclosure">Disclosure</a></li>
  <li><a href="#acknowledgments" id="toc-acknowledgments" class="nav-link" data-scroll-target="#acknowledgments">Acknowledgments</a></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="reviews/round-1/code-cert-skeptic-preview.html"><i class="bi bi-journal-code"></i>Adversarial audit: /Users/maxghenis/.cache/axiom-oracles/v2b/CERT_REPORT.md</a></li><li><a href="reviews/round-1/code-stats-redteam-preview.html"><i class="bi bi-journal-code"></i>Adversarial statistical review: snap-qc-sim (main @ 026a362, post PR #9)</a></li><li><a href="reviews/round-1/referee-citations-preview.html"><i class="bi bi-journal-code"></i>Citation Review — snap-qc-sim paper</a></li><li><a href="reviews/round-1/code-claims-sweep-preview.html"><i class="bi bi-journal-code"></i>Claims audit — snap-qc-sim (main @ 026a362)</a></li><li><a href="snapshot/cert/CERT_REPORT-preview.html"><i class="bi bi-journal-code"></i>CO SNAP QC certification: CERTIFIED</a></li><li><a href="reviews/round-1/referee-domain-preview.html"><i class="bi bi-journal-code"></i>Domain expert review: SNAP program and quality-control specialist</a></li><li><a href="FACTS-preview.html"><i class="bi bi-journal-code"></i>Fact catalog</a></li><li><a href="reviews/round-1/code-js-fidelity-preview.html"><i class="bi bi-journal-code"></i>Fidelity audit: app.js model mode vs analysis/predictive_process.py</a></li><li><a href="reviews/round-4/methodology-preview.html"><i class="bi bi-journal-code"></i>Methodology review — revision-4 delta (verbatim, 2026-08-09)</a></li><li><a href="reviews/round-2/round2-methodology-preview.html"><i class="bi bi-journal-code"></i>Methodology review — round 2 (revised manuscript, commit 27e1b09)</a></li><li><a href="reviews/round-1/referee-methodology-preview.html"><i class="bi bi-journal-code"></i>Methodology review: "Administrative quality control data as an oracle" (paper/index.qmd)</a></li><li><a href="reviews/round-1/referee-neutrality-preview.html"><i class="bi bi-journal-code"></i>Neutrality Review</a></li><li><a href="snapshot/qrf-cross-process-attestation-preview.html"><i class="bi bi-journal-code"></i>QRF benchmark cross-process determinism attestation</a></li><li><a href="reviews/round-4/red-team-preview.html"><i class="bi bi-journal-code"></i>Red-team review — revision-4 delta (verbatim, 2026-08-09)</a></li><li><a href="reviews/round-2/round2-redteam-preview.html"><i class="bi bi-journal-code"></i>Red-Team Review — Round 2 (revised manuscript, commit 27e1b09)</a></li><li><a href="reviews/round-1/referee-redteam-preview.html"><i class="bi bi-journal-code"></i>Red-Team Review: "Administrative quality control data as an oracle" (paper/index.qmd @ bce8eb6, origin/paper)</a></li><li><a href="reviews/round-1/referee-reproducibility-preview.html"><i class="bi bi-journal-code"></i>Reproducibility Review</a></li><li><a href="reviews/round-3/methodology-preview.html"><i class="bi bi-journal-code"></i>Round 3 — methodology review (revision-3 changed regions)</a></li><li><a href="reviews/round-3/red-team-preview.html"><i class="bi bi-journal-code"></i>Round 3 — red-team review (revision-3 changed regions)</a></li><li><a href="reviews/round-3/round-diff-preview.html"><i class="bi bi-journal-code"></i>Round 3 — round-diff review (alignment-pass @ 084c6bb)</a></li><li><a href="reviews/round-1/EDITORIAL-preview.html"><i class="bi bi-journal-code"></i>Round-1 editorial synthesis</a></li><li><a href="reviews/round-5/methodology-preview.html"><i class="bi bi-journal-code"></i>Round-5 methodology referee report</a></li><li><a href="reviews/round-5/neutrality-preview.html"><i class="bi bi-journal-code"></i>Round-5 neutrality and style referee report</a></li><li><a href="reviews/round-5/red-team-preview.html"><i class="bi bi-journal-code"></i>Round-5 red-team referee report</a></li><li><a href="reviews/round-5/SUMMARY-preview.html"><i class="bi bi-journal-code"></i>Round-5 referee summary</a></li><li><a href="reviews/round-5/reproducibility-preview.html"><i class="bi bi-journal-code"></i>Round-5 reproducibility referee report</a></li><li><a href="reviews/round-5/round-diff-preview.html"><i class="bi bi-journal-code"></i>Round-5 revision-difference referee report</a></li><li><a href="reviews/round-6/RESOLUTIONS-preview.html"><i class="bi bi-journal-code"></i>Round-6 resolutions (maintainer adjudication, 2026-08-14)</a></li><li><a href="reviews/round-2/round2-rounddiff-preview.html"><i class="bi bi-journal-code"></i>Round-Diff Review: round-1 resolution audit (paper branch @ 27e1b09)</a></li><li><a href="reviews/round-1/referee-stylistic-preview.html"><i class="bi bi-journal-code"></i>Stylistic review: "Administrative quality control data as an oracle"</a></li><li><a href="reviews/round-6/SUMMARY-preview.html"><i class="bi bi-journal-code"></i>SUMMARY.md</a></li><li><a href="snapshot/labs/amterr/ANALYSIS-preview.html"><i class="bi bi-journal-code"></i>What share of SNAP payment errors could a verified rules engine prevent?</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Under 7 U.S.C. § 2013(a)(2), as amended by the One Big Beautiful Bill Act (Pub. L. No.&nbsp;119-21, 2025; OBBBA), a state whose SNAP payment error rate reaches 6% will pay 5% of benefit costs beginning in fiscal year 2028; at 8%, the share is 10%; at 10%, it is 15%. The rate that determines the FY2028 share is the state’s fiscal 2025 or 2026 rate, at its election; later years use the third preceding year. Implementation is delayed for the highest-error states: a state whose fiscal 2025 rate times 1.5 reaches 20% — that is, a rate above 13.33% (13.34% at the published two-decimal precision) — starts in FY2029 instead, and a state whose fiscal 2026 rate crosses the same test starts in FY2030.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> For a mid-sized state, one tier is worth tens of millions of dollars a year; for the largest states, more than a hundred million.</p>
<p>The error rate is estimated by the Quality Control system: each state re-reviews a probability sample of its own active cases — by formula in 7 C.F.R. § 275.11, between 300 and 2,400 annually, or 300 to 1,020 under an optional reduced schedule that every state elected in fiscal 2024 <span class="citation" data-cites="fns2024techdoc">(<a href="#ref-fns2024techdoc" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Service 2025b</a>)</span> — and federal reviewers re-review a subsample, from which the Food and Nutrition Service (FNS; renamed the Food and Nutrition Administration in 2026 — the fiscal 2025 rate publication carries the new letterhead <span class="citation" data-cites="fna2025per">(<a href="#ref-fna2025per" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Administration 2026</a>)</span>, and this paper keeps FNS, the name on every document the fiscal 2024 data cite) estimates official state rates with adjustments including federal re-review integration. The public-use files that result record, for roughly 45,000 cases a year, what the agency issued and what the review concluded the case should have received, with coded findings for every discrepancy.</p>
<p>This paper treats those files as a research instrument with three uses, the first in the software-testing sense of an <em>oracle</em>: an external source of ground-truth outputs for given inputs.</p>
<p>First, as a verification target for rules as code. I test independently encoded SNAP rules — statute, regulations, and state policy manuals encoded as executable rule modules — against the QC file’s recorded benefit computations in seven states, holding the bar at exact reproduction: zero dollar tolerance across six computation stages per case (<a href="#sec-oracle" class="quarto-xref">Section&nbsp;4</a>). The target’s precise character matters and is stated in <a href="#sec-oracle-scope" class="quarto-xref">Section&nbsp;4.1</a>: the file’s benefit chain is the FNS QC Minimodel’s computation on edited, internally consistent case records, so parity certifies agreement with the agency’s own computational canon, not independent adjudication. Reaching it surfaced defects on three sides: two in the encodings under test, errata in the federal technical documentation, and a residue attributable to state issuance systems.</p>
<p>Second, as raw material for decomposing measured error. QC’s own cause coding, a finding-nature classification, and a replay of reconstructed pre-edit case facts through the verified engine give three nested estimates of how much of the error rate reflects computation failure versus wrong facts correctly processed (<a href="#sec-decompose" class="quarto-xref">Section&nbsp;5</a>).</p>
<p>Third, as training and validation data for a case-level model of the error process (<a href="#sec-model" class="quarto-xref">Section&nbsp;6</a>) and the basis for a distributional simulator of measured rates under the cost-sharing formula (<a href="#sec-simulate" class="quarto-xref">Section&nbsp;7</a>), public at policyengine.org/us/snap-payment-error-simulator. The simulator’s central output is a measurement result: near tier boundaries, sampling noise alone gives several states nearly even odds of a different cost tier than their point rate implies.</p>
<p>The analysis pipeline, simulator, and this manuscript live in one public repository; a fact catalog maps every quantitative claim to a committed artifact (<a href="#sec-availability" class="quarto-xref">Section&nbsp;11</a>). The pipeline is deterministic — independent clean-room reruns reproduce every analysis artifact byte-for-byte, and the headline simulation artifact was independently reproduced from the raw file to four decimals — and the manuscript has been through six rounds of adversarial review, archived unedited in the repository.</p>
</section>
<section id="sec-related" class="level2">
<h2 class="anchored" data-anchor-id="sec-related">Related work</h2>
<p>Cost sharing keyed to noisy error rates is not a new experiment; it is a return. The first sanction regime tied state liability to food stamp error rates against thresholds that stepped from 9% to 7% to 5% across fiscal 1983–85, with waiver machinery absorbing the disputes that followed <span class="citation" data-cites="gao1984liability">(<a href="#ref-gao1984liability" role="doc-biblioref">U.S. General Accounting Office 1984</a>)</span>. A National Research Council panel convened to rethink that system concluded it needed replacing <span class="citation" data-cites="nrc1987rethinking">(<a href="#ref-nrc1987rethinking" role="doc-biblioref">National Research Council 1987</a>)</span>, and the 2002 Farm Bill narrowed liability to persistently high-error states: where the prior rule had sanctioned roughly half of states each year for exceeding the national average, the new one required a 95 percent statistical probability that a state’s rate exceeded 105 percent of the national average for two consecutive years <span class="citation" data-cites="gao2007errors">(<a href="#ref-gao2007errors" role="doc-biblioref">U.S. Government Accountability Office 2007</a>)</span>. That redesign wrote sampling uncertainty into the liability rule itself; the 2025 statute reverses the narrowing at larger scale and prices point estimates. This paper runs the measurement analysis that difference demands: case-level noise quantification against the tiers the money now hangs on.</p>
<p>The measurement system also has a documented behavioral record. After a nationwide USDA Inspector General audit, the Department of Justice brought False Claims Act cases alleging that states, working with outside quality-control consultants, improperly diminished identified errors; eight states and a consulting firm paid more than $67 million to resolve those allegations <span class="citation" data-cites="doj2021snapqc crs2018errors">(<a href="#ref-doj2021snapqc" role="doc-biblioref">U.S. Department of Justice 2021</a>; <a href="#ref-crs2018errors" role="doc-biblioref">Congressional Research Service 2018</a>)</span>, including Texas’s $15.3 million settlement over performance bonuses the government alleged were claimed on biased error data <span class="citation" data-cites="doj2019texas">(<a href="#ref-doj2019texas" role="doc-biblioref">U.S. Department of Justice 2019</a>)</span>. That history motivates two choices here: the error models predict an adjudicated label, a property of the measurement system rather than of households, and the strategic response of measurement to incentives is a registered design target (the fiscal 2026 pre-registration, <a href="#sec-fy2025" class="quarto-xref">Section&nbsp;7.1</a>) rather than a footnote.</p>
<p>Measurement noise in accountability systems has a standard reference point: school ratings reward and punish schools for sampling variation <span class="citation" data-cites="kane2002volatility">(<a href="#ref-kane2002volatility" role="doc-biblioref">Kane and Staiger 2002</a>)</span>. The cost-sharing formula raises the stakes of that observation — the draw prices directly, in nine-figure annual bills — and the case files permit what ratings literatures usually lack, a decomposition of the measured quantity into computation, information, and adjudication layers.</p>
<p>On the error process itself, the administrative-burden literature supplies the strongest identified result: randomly assigned recertification interview timing changes SNAP participation by over 20 percent among affected cases <span class="citation" data-cites="homonoff2021recertification">(<a href="#ref-homonoff2021recertification" role="doc-biblioref">Homonoff and Somerville 2021</a>)</span>, grounding the churn channel this paper’s models treat as feature material — and grounding a reading of Kentucky’s post-migration extension of recertification periods as an error-relevant intervention, not only a workload one. The event-study machinery follows the synthetic-control canon <span class="citation" data-cites="abadie2010synthetic abadie2021using">(<a href="#ref-abadie2010synthetic" role="doc-biblioref">Abadie et al. 2010</a>; <a href="#ref-abadie2021using" role="doc-biblioref">Abadie 2021</a>)</span>, and the committed prediction artifact follows the forecasting-before-results line <span class="citation" data-cites="dellavigna2018predicting dellavigna2020forecasting">(<a href="#ref-dellavigna2018predicting" role="doc-biblioref">DellaVigna and Pope 2018</a>; <a href="#ref-dellavigna2020forecasting" role="doc-biblioref">DellaVigna et al. 2020</a>)</span> with a different object: model-derived, hash-pinned predictions for a policy regime rather than elicited expert forecasts for experiments. The verification oracle framing extends rules-as-code correctness work <span class="citation" data-cites="merigoux2021catala">(<a href="#ref-merigoux2021catala" role="doc-biblioref">Mérigoux, Chataing, et al. 2021</a>)</span> by holding encodings to an external administrative record rather than to internal consistency.</p>
</section>
<section id="sec-qc" class="level2">
<h2 class="anchored" data-anchor-id="sec-qc">The QC system and the money attached to it</h2>
<p>QC reviews produce, for each sampled active case, the issued allotment and a corrected allotment constructed from the reviewer’s findings; when they differ by more than a tolerance threshold ($56 in fiscal 2024, indexed from a $37 statutory base under 7 U.S.C. § 2025(c)),<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> the case is a payment error, and findings are coded for sub-threshold deviations as well. <a href="#tbl-codebook" class="quarto-xref">Table&nbsp;1</a> lists the public-use file variables this paper works with; variable names in the text refer to these columns. The official state rate combines over- and underpayment rates <span class="citation" data-cites="fns2024per">(<a href="#ref-fns2024per" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Service 2025a</a>)</span>: Colorado’s 9.97% is 7.91 over plus 2.06 under, and Maryland’s 13.64 includes the nation’s highest underpayment rate, 4.79 — so cost sharing partly bills states for underpaying their own residents.</p>
<div id="tbl-codebook" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-codebook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Public-use QC file variables used in this paper (fiscal 2024 technical documentation).
</figcaption>
<div aria-describedby="tbl-codebook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>What the file records</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>RAWBEN</code></td>
<td>the allotment the state actually issued</td>
</tr>
<tr class="even">
<td><code>BENFIX</code></td>
<td>the allotment corrected for the reviewer’s findings</td>
</tr>
<tr class="odd">
<td><code>AMTERR</code></td>
<td>the recorded error amount</td>
</tr>
<tr class="even">
<td><code>FSBEN</code></td>
<td>the formula benefit recomputed by the FNS QC Minimodel from the case’s edited inputs</td>
</tr>
<tr class="odd">
<td><code>STATUS</code></td>
<td>the review disposition (correct, overpayment, underpayment)</td>
</tr>
<tr class="even">
<td><code>ELEMENT1-9</code>, <code>E_FINDG1-9</code>, <code>AMOUNT1-9</code></td>
<td>up to nine coded error findings: the element in error, the nature of the finding, and its dollar amount</td>
</tr>
<tr class="odd">
<td><code>HWGT</code></td>
<td>the case weight</td>
</tr>
<tr class="even">
<td><code>FSGRINC</code>, <code>FSSTDDED</code>, <code>FSNETINC</code> and companions</td>
<td>the recorded benefit-computation chain: gross income, deductions, net income, maximum allotment</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Four features of the system frame everything that follows.</p>
<p><strong>The public file is not the full review universe.</strong> The edited public-use file excludes cases with ineligible findings — for which the official methodology scores the <em>entire</em> issued benefit as error dollars — cases whose overissuance equals or exceeds the issued benefit, incomplete reviews, and internal-consistency drops <span class="citation" data-cites="fns2024techdoc">(<a href="#ref-fns2024techdoc" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Service 2025b</a>)</span>. In fiscal 2024 this removed 1,037 ineligible-finding and 406 full-overissuance cases nationally. The file is therefore truncated at the top of the error-magnitude distribution. Every file-based estimate in this paper inherits that truncation: it is part of why Colorado’s file-derived rate (8.88%) sits below its official 9.97%. Restoring the excluded cases would add a large between-component variance term — their per-case error contributions are the full issued benefit — so the truncation biases simulated sampling variability downward; the i.i.d. approximation to states’ month-stratified sampling designs plausibly biases it upward, so the tier-noise results of <a href="#sec-simulate" class="quarto-xref">Section&nbsp;7</a> are likely, though not certainly, understated.</p>
<p><strong>The measured rate is a property of the measurement system.</strong> Between roughly 2009 and 2016, several states used consultant-driven error-review practices that biased QC findings downward; the Department of Justice recovered more than $67 million in False Claims Act settlements from eight states over 2017–2021 <span class="citation" data-cites="doj2021snapqc">(<a href="#ref-doj2021snapqc" role="doc-biblioref">U.S. Department of Justice 2021</a>)</span>, FNS issued formal anti-bias guidance, and national rates for fiscal 2015–16 were not published <span class="citation" data-cites="crs2018errors">(<a href="#ref-crs2018errors" role="doc-biblioref">Congressional Research Service 2018</a>)</span>. This history is why the present analysis trains no earlier than fiscal 2017 — and why the fiscal 2025–27 rates now being measured, which carry orders of magnitude more money than the settlements-era rates did, cannot be treated as exogenous to the incentive they price.</p>
<p><strong>Only active cases are priced.</strong> The QC system also reviews negative actions — denials, terminations, suspensions — feeding a separate case-and-procedure error rate that OBBBA does not price. A state can therefore lower its priced error rate by tightening the front door, shifting error into the unpriced metric. This paper analyzes the priced, active-case system; the asymmetry belongs on any list of the formula’s incentive properties.</p>
<p><strong>Precision was contractually waived.</strong> A state electing the reduced sampling schedule agrees not to dispute later error-rate findings on the basis of the precision of the estimates <span class="citation" data-cites="fns2024techdoc">(<a href="#ref-fns2024techdoc" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Service 2025b</a>)</span>. All 53 jurisdictions had so elected as of fiscal 2024 — a defensible economy when QC reviews were an administrative cost with no tier attached, and a striking one now that precision determines tier placement worth tens of millions of dollars. The cost calculus has since moved <em>against</em> precision even as its value rose: OBBBA cut the federal share of SNAP administrative costs — QC review staffing included — from 50% to 25% beginning fiscal 2027 (Pub. L. No.&nbsp;119-21 § 10106), so each additional review now costs a state three dollars where it used to cost two. Whether states revert to the standard schedule — regaining precision and dispute rights at that higher marginal price — is a live sampling-plan question, and exactly the one <a href="#sec-simulate" class="quarto-xref">Section&nbsp;7</a> prices with its additional-reviews lever.</p>
</section>
<section id="sec-oracle" class="level2">
<h2 class="anchored" data-anchor-id="sec-oracle">The QC file as a verification oracle</h2>
<p>Rules as code — encoding statutes and regulations as executable, testable logic — has a recognized validation problem: against what do you test the encoding? Unit tests encode the encoder’s own reading of the law, and cross-model comparisons inherit both models’ assumptions; the literature has approached validation by compiling legal text alongside experts <span class="citation" data-cites="merigoux2021catala oecd2020cracking">(<a href="#ref-merigoux2021catala" role="doc-biblioref">Mérigoux, Chataing, et al. 2021</a>; <a href="#ref-oecd2020cracking" role="doc-biblioref">Mohun and Roberts 2020</a>)</span> and, closest to this paper, by testing an independent encoding of the French tax code against the tax authority’s own published test cases <span class="citation" data-cites="merigoux2021compiler">(<a href="#ref-merigoux2021compiler" role="doc-biblioref">Mérigoux, Monat, et al. 2021</a>)</span>. Administrative QC data extends that strategy to a benefits program at case level: tens of thousands of real cases per year, each carrying inputs and the agency’s own computed outputs.</p>
<p>I tested encodings of federal SNAP law and seven states’ policy manuals (Arizona, California, Colorado, Georgia, Maryland, New York, Texas), maintained by The Axiom Foundation in its public rulespec-us repository and executed by its deterministic rules engine, against the fiscal 2024 QC file. The file contains 6,194 cases in the official universe for those states; 6,081 are in scope for replay — all 113 exclusions (1.8%) are SSI-CAP (Combined Application Project) standardized-benefit units, whose allotments follow a demonstration schedule outside the computed chain, logged per case by the harness. <a href="#tbl-verify" class="quarto-xref">Table&nbsp;2</a> reports the counts. For each in-scope case the harness asserts six values — gross income, standard deduction, excess shelter deduction, net income, maximum allotment, and benefit — against the file’s recorded values at zero dollar tolerance. These six are the stage outputs the public file records for the computed chain; adjudication-dependent amounts the reviewer establishes as facts — claimed medical expenses, utility allowances, child-support obligations, eligibility findings — enter as inputs rather than assertions. The assertion surface can widen as encodings and file coverage allow (the earned-income deduction, for instance, is mechanical given earnings), and the excluded SSI-CAP units are themselves encodable: their demonstration benefit schedules are published in the technical documentation, so bringing them in scope — for both verification and simulation — is an encoding task, not a data gap.</p>
<p>All 6,081 in-scope cases match on all six asserted values — 36,486 exact cell comparisons, no mismatches.</p>
<div id="tbl-verify" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-verify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Fiscal 2024 verification coverage by state. All exclusions are SSI-CAP standardized-benefit units, logged per case by the harness.
</figcaption>
<div aria-describedby="tbl-verify-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>State</th>
<th style="text-align: right;">In-scope cases replayed exactly</th>
<th style="text-align: right;">Official-universe cases</th>
<th style="text-align: right;">Excluded</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Arizona</td>
<td style="text-align: right;">922</td>
<td style="text-align: right;">925</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td>California</td>
<td style="text-align: right;">883</td>
<td style="text-align: right;">883</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>Colorado</td>
<td style="text-align: right;">856</td>
<td style="text-align: right;">856</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td>Georgia</td>
<td style="text-align: right;">945</td>
<td style="text-align: right;">945</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>Maryland</td>
<td style="text-align: right;">722</td>
<td style="text-align: right;">745</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="even">
<td>New York</td>
<td style="text-align: right;">847</td>
<td style="text-align: right;">885</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="odd">
<td>Texas</td>
<td style="text-align: right;">906</td>
<td style="text-align: right;">955</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td>Total</td>
<td style="text-align: right;">6,081</td>
<td style="text-align: right;">6,194</td>
<td style="text-align: right;">113</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="sec-oracle-scope" class="level3">
<h3 class="anchored" data-anchor-id="sec-oracle-scope">What the parity target is</h3>
<p>Exactness claims invite overreading, so the scope deserves a precise statement — more precise than an earlier draft of this paper gave it.</p>
<p>The compared benefit chain is the one recorded in the edited public-use file, whose benefit variable (<code>FSBEN</code>) is computed by the FNS QC Minimodel — the agency’s own benefit-calculation software — and whose editing process reconciles case records until internal identities hold, adjusting deduction fields in a documented sequence until the calculated benefit matches the raw benefit within $5 <span class="citation" data-cites="fns2024techdoc">(<a href="#ref-fns2024techdoc" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Service 2025b</a>)</span>. The comparison also supplies several intermediates directly from the file rather than deriving them from raw facts: the QC-calculated medical and child-support deduction amounts, the recorded utility allowance, and the recorded categorical-eligibility status; eligibility screens receive passing defaults, since every filed case was enrolled.</p>
<p>Parity therefore certifies the following: that the encoded computation chain — income aggregation, deduction sequencing, net-income arithmetic, allotment lookup, rounding — agrees exactly with the agency’s own computational canon, over the full diversity of 6,081 real case configurations, parameter values, and boundary conditions. It is an agreement between two implementations of the same rules, closer in kind to the cross-model comparisons this method extends than to independent adjudication of case outcomes; what distinguishes it from ordinary cross-model comparison is the counterparty (the agency’s own canon), the case realism, and the zero-tolerance bar. It does not certify independent derivation of every state eligibility and deduction pathway from raw facts. Extending the harness to feed raw facts — recorded medical expenses rather than the computed deduction, energy-assistance facts rather than the utility tier — is the necessary next step before the engine can compute counterfactual intermediates under alternative policy (<a href="#sec-roadmap" class="quarto-xref">Section&nbsp;8</a>). The reviewer-adjudicated quantities in the file (<code>RAWBEN</code>, <code>BENFIX</code>, error amounts and findings) are not the parity target; they are the subject of <a href="#sec-decompose" class="quarto-xref">Section&nbsp;5</a>.</p>
<p>Holding tolerance at zero is what made the exercise informative. Early runs did not match, and each mismatch class was a finding about somebody’s rules: two defects in the encodings under test (a regulatory dollar literal superseded by statute, and a missing whole-dollar rounding step — both fixed in the public repository, with the oracle as the detector), errata in the technical documentation’s variable descriptions (reported upstream), and — once the encodings reproduced the file’s chain exactly — a residue in <em>issued</em> amounts attributable to the issuing side, which <a href="#sec-decompose" class="quarto-xref">Section&nbsp;5</a> takes up. The corrections were global rule fixes, not case-specific accommodations; still, the exactness result is post-correction on the same case set, a reuse the certification protocol mitigates but does not eliminate. A confirmatory run on the fiscal 2025 file at its release is the committed next test.</p>
<p>The toolchain is certified for reproduction: a pinned engine build and encoding-repository commit reproduce the Colorado suite — 856 cases, 5,136 cells including the 856 benefit cells — under recorded hashes for every input, with an independent audit rebuilding the engine to a byte-identical binary and re-running the comparison to byte-identical evidence. Throughput is 230 cases per second end to end on a laptop, so verification at this scale is not compute-bound for this workload; details and timing calibration are in the repository’s certification report.</p>
</section>
</section>
<section id="sec-decompose" class="level2">
<h2 class="anchored" data-anchor-id="sec-decompose">Decomposing measured error: computation versus facts</h2>
<p>If a verified engine issued every benefit, how much measured error would disappear? The QC file supports three nested answers for Colorado fiscal 2024, summarized in <a href="#tbl-decompose" class="quarto-xref">Table&nbsp;3</a>: 305 of 856 sampled cases carry recorded payment deviations (<code>RAWBEN</code> ≠ <code>BENFIX</code>) — but only 110 of the 305 are official errors above the $56 threshold; the other 195 are sub-threshold deviations the official rate excludes. Weighted, the 305 carry $112.6M per year in deviation dollars on $1.268B of issuance, of which $18.5M (16%) is sub-threshold: the deviation-based 8.88% file rate therefore combines an official-definition file rate of 7.42% with sub-threshold dollars, while the official 9.97% additionally incorporates the federal re-review adjustment and the excluded ineligible-case error of <a href="#sec-qc" class="quarto-xref">Section&nbsp;3</a>. All three layers exclude, by construction of the file, that ineligible-case error.</p>
<div id="tbl-decompose" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-decompose-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Three nested decompositions of Colorado fiscal 2024 measured error. Layers 1–2 quote the committed cause-share artifact (<code>analysis/cause_shares.json</code>, all 53 jurisdictions, conventions and code-to-class maps serialized in the file); layer 3 is a share of filtered cases. Any-presence attribution counts a case’s dollars toward every cause class present in its slots, so layer-1 classes overlap. Layer 2 partitions cases; its system-side test reuses layer 1’s broad computing-apparatus cause set — the artifact also carries a wider agency-responsibility convention under which the system-side shares are several times larger (Colorado system-caused input 31% rather than 6.6%), answering a responsibility question rather than this table’s computation question. Cause and nature coding reflect state reviewer judgment under handbook guidance <span class="citation" data-cites="fns310handbook">(<a href="#ref-fns310handbook" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Service 2023</a>)</span> and carry cross-state coding variation; fiscal 2024 also brought minor revisions to the finding-code sets.
</figcaption>
<div aria-describedby="tbl-decompose-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Layer</th>
<th>Definition</th>
<th>Computation-side share</th>
<th>Universe and units</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Cause codes</td>
<td>QC agency-cause codes naming the computing apparatus (programming, arithmetic, mass change), any-presence across a case’s nine cause slots, share of official error dollars (HWGT × <code>AMTERR</code>)</td>
<td>7.4% strict ($6.9M/yr); 10.6% ($10.0M/yr) adding policy-misapplied, budgeted-wrong, computer-user</td>
<td>Colorado; nationally 3.5% strict ($232M/yr), 19.3% broad ($1.27B of $6.59B)</td>
</tr>
<tr class="even">
<td>2. Finding natures</td>
<td><code>NATURE</code> codes inherently describing computation (rounding, conversion, wrong standard, benefit miscomputed) plus the arithmetic <code>ELEMENT</code>; deduction-amount natures count only when the paired cause is in layer 1’s broad computing-apparatus set</td>
<td>3.3% pure-computation; 6.6% system-caused input; 4.2% mixed; 86.0% other input</td>
<td>Colorado weighted deviation dollars; nationally 4.6% / 11.1% / 6.5% / 77.7%</td>
</tr>
<tr class="odd">
<td>3. Engine replay</td>
<td>Reconstructed pre-edit facts replayed through the verified engine and compared to issued amounts</td>
<td>Above-threshold official errors: 21.6% of cases unexplained (upper bound), 78.4% explained as correct arithmetic on wrong facts. Sub-threshold deviations: 8.6% unexplained, 91.4% explained. Blended: 13.1% / 86.9%</td>
<td>283 filtered Colorado deviation cases (97 above threshold, 186 below); case shares, not dollar shares</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The strictest layer reconstructs each error case’s pre-edit original values using the public reconstruction solver of <span class="citation" data-cites="giannella_snapqc">Giannella and Molin (<a href="#ref-giannella_snapqc" role="doc-biblioref">2026</a>)</span> — which exploits the file’s disclosure-protection perturbation structure to recover original values — adapted to fiscal 2024, then replays those originals through the verified engine. Of 283 deviation cases surviving the solver’s consistency filters (22 of 305 are excluded), 246 reproduce the issued amount at the file’s own $5 editing tolerance: the agency’s arithmetic was correct, applied to wrong facts. The rate differs by threshold status, and the distinction matters for how the headline reads: among the 97 above-threshold official error cases, 76 are explained (78.4%, binomial standard error about 4 points; the 21.6% residual is the computation-side upper bound for <em>official</em> errors), while among the 186 sub-threshold deviations 170 are explained (91.4%). The solver and the engine partition the 283 cases identically — two implementations with distinct codebases and logic reaching the same classification, though both consume the same file, and 33 of the 246 explained cases have deviations of $5 or less, mechanically within the comparison tolerance. The residual class includes solver limitations as well as genuine multi-variable or computational discrepancies. The complete per-case replay output (283 rows), the layer-1 and layer-2 classification outputs, and the reconstruction scripts are committed with this paper.</p>
<p>The three layers agree on the structure: most measured SNAP payment error among eligible cases is information failure, not calculation failure — consistent with the administrative-burden literature’s account of where compliance costs bind <span class="citation" data-cites="herd2018burden">(<a href="#ref-herd2018burden" role="doc-biblioref">Herd and Moynihan 2018</a>)</span>. Correct-computation guarantees address the smaller share directly — roughly 3 to 10% of error dollars by layers 1–2, and bounded above by the replay’s 21.6% case share among official errors — plus whatever share of information failures better tooling prevents indirectly through verification prompts and documentation-requirement computation at intake; <a href="#sec-adoption" class="quarto-xref">Section&nbsp;7.2</a> prices the direct shares through the formula’s tiers, elections, and delay clause. Ineligibility errors, excluded from the file, are predominantly facts-driven, which would push the information-failure share higher still; that inference, unlike the in-file shares, is not directly computed here. The indirect channel is where policy design enters: rules determine what a caseworker must collect and verify, which is the mechanism the modeling section takes up.</p>
</section>
<section id="sec-model" class="level2">
<h2 class="anchored" data-anchor-id="sec-model">Modeling the error process</h2>
<p>Pricing decisions — what a documentation requirement costs in error, what an audit-volume change buys — require a model of the error-generating process at case level. I fit one on the QC files for 2017–2019 and 2022–2023 (pandemic years excluded), evaluating on fiscal 2024: 217,656 training and 44,800 evaluation cases in the official universe, all estimates weighted by the file’s case weights, with models estimated in scikit-learn <span class="citation" data-cites="pedregosa2011sklearn">(<a href="#ref-pedregosa2011sklearn" role="doc-biblioref">Pedregosa et al. 2011</a>)</span>. Fiscal 2024 informed pipeline development across the audit-and-correction rounds and is not a pristine holdout. The committed next test is a frozen-pipeline confirmation on the fiscal 2025 file, and its harness is built and waiting: the four scoring modules are hash-frozen, the runner refuses drifted code, and replaying fiscal 2024 through it reproduces the committed reference values exactly — publication day is one command against frozen code; the one-shot, no-re-tuning discipline is a stated commitment the harness supports rather than enforces, and anything after the first run is labeled post hoc.</p>
<p>The modeled object is the per-case distribution of what the state issued relative to what the review concluded it should have: the signed deviation <span class="math inline">\(D = \texttt{RAWBEN} - \texttt{BENFIX}\)</span>, whose distribution — given the corrected benefit — is the distribution of issuance itself. <span class="math inline">\(D\)</span> reconciles with the file’s recorded error amount for 99.997% of weighted fiscal 2024 cases. The recomputed formula benefit <code>FSBEN</code> is not a usable target — <span class="math inline">\(|\texttt{RAWBEN} - \texttt{FSBEN}|\)</span> matches the recorded error amount for only 83.64%, because it conflates legitimate adjustments such as proration with error — but it serves as a model feature, anchoring each case’s formula benefit. A committed case-by-case catalog quantifies the conflation for the seven verified states (<code>analysis/engine_comparison.json</code>, served in the deployed simulator’s engine view): per state, <code>BENFIX</code> reconciles with the recorded error amount exactly while <code>FSBEN</code> concordance runs 0.80–0.91, with 881 of the 6,194 official-universe cases diverging — the comparison reads only file columns, so it covers the 113 replay-excluded SSI-CAP cases as well — classified by the file’s own coding into allotment adjustments, error corrections, and recorded-correct nonformula cases. The official error label (reviewer status with an amount above the year’s threshold) defines the binary outcome used for discrimination checks.</p>
<p><strong>Discrimination.</strong> A gradient-boosted classifier of the official error label on household covariates plus the formula-benefit anchor reaches a weighted area under the receiver operating characteristic curve (ROC AUC) of 0.761 on fiscal 2024; adding policy-burden intermediates extracted from the file (medical-expense claiming and documentation-requirement proxies, self-employment records, utility-claim structure, deduction counts) moves it to 0.767 (+0.006 AUC, +0.003 PR-AUC). At a 5% weighted review budget the classifier reaches 47.8% precision against a 13.4% weighted base rate — case targeting at three and a half times chance, though QC-sampled cases are not the operational targeting population and the estimate carries no design-based standard error.</p>
<p><strong>The deviation distribution.</strong> For simulation I estimate a per-case distribution of the signed deviation with a hurdle structure: a deviation probability <span class="math inline">\(P(|D| &gt; 0.5)\)</span> and an above-threshold probability, each estimated by gradient boosting with nested out-of-fold isotonic calibration; a sign model (calibrated AUC 0.700 in the shipped frozen configuration); nine conditional quantiles of <span class="math inline">\(\log|D|\)</span> fitted by quantile-loss gradient boosting <span class="citation" data-cites="koenker1978quantile">(<a href="#ref-koenker1978quantile" role="doc-biblioref">Koenker and Bassett 1978</a>)</span>, made monotone per case by rearrangement <span class="citation" data-cites="chernozhukov2010rearrange">(<a href="#ref-chernozhukov2010rearrange" role="doc-biblioref">Chernozhukov et al. 2010</a>)</span>; and an exponential tail in logs beyond the 99th percentile. Conditional magnitudes retransform with an out-of-fold Duan smear of 1.173 <span class="citation" data-cites="duan1983smearing">(<a href="#ref-duan1983smearing" role="doc-biblioref">Duan 1983</a>)</span>; predicted mean conditional magnitude is $186 against $189 observed. The tail is fitted at the depth where it attaches (log scale 0.252), each case’s magnitude is capped at a physical maximum, and state dollar-rate factors are fit on out-of-sample fiscal 2023 predictions and frozen.</p>
<p><strong>Validation, including failures.</strong> <a href="#tbl-validate" class="quarto-xref">Table&nbsp;4</a> summarizes, for the configuration that ships: the frozen model trained through fiscal 2022 (62,984 training deviators), with fiscal 2023 held out for factor fitting and fiscal 2024 for evaluation. Coverage of the conditional quantiles fails: within 3 points of nominal at only two of nine levels, all nine gaps negative (−0.38 to −7.30 points, worst at the 75th–90th percentiles). This is one-sided <em>under</em>-coverage — predicted quantiles sit too low, understating mid-to-upper magnitudes, coherent with the $186-versus-$189 comparison. The under-coverage is not specific to the gradient-boosted quantile stack: under a pre-specified decision rule, a quantile regression forest on the identical protocol (benchmarked against the model without the three certification/BBCE/premium feature families) improves mean absolute coverage (4.10 against 4.38 points) but shifts under-coverage from the tail to the central levels with a worse maximum gap, degrades probability-integral-transform calibration, and loses the factor-adjusted state dollar-rate comparison (0.951 against 0.928 points — a different object from <a href="#tbl-validate" class="quarto-xref">Table&nbsp;4</a>’s official-error-rate MAE), so the gradient-boosted stack is retained; causes the two estimators share — the feature set, the tree-ensemble family, the temporal gap from the frozen training window to fiscal 2024 — remain candidates.</p>
<p>Two pre-registered repair experiments, each with its protocol committed before its results (the two-commit ordering survives squash merges in the pull-request refs, #53 and #55), interrogate the failure. A dispersion round tested a conformal remap of nominal quantile levels and per-state spread inflation, fit on leave-one-year-out training folds; its mechanical winner improved the mean absolute gap to 4.08 points while collapsing fifth-percentile coverage from 4.6% to 0.02%, and adoption was declined in a decision recorded beside the frozen protocol. The round’s real product is a diagnostic: every mechanism leaves all nine gaps negative, so the failure behaves as location rather than width under every tested mechanism. A location round followed under per-level guards — no level may worsen more than half a point, no new over-3-point flags, a lower-tail coverage floor — and a single global shift of +0.038 log dollars wins them cleanly: the mean absolute gap falls from 4.64 to 3.80 points with every level improving (the median level from −7.11 to −5.62), while two more flexible mechanisms posted lower means and failed the per-level guards the second protocol added. The repaired calibration is committed and stays out of the scoring path until the fiscal 2025 confirmation runs against the frozen modules. The residual — every gap still negative, the deepest misses at the middle levels — reads as data limitation rather than estimator choice, and partner-state administrative records are the strongest available data against it.</p>
<p>The deployed simulator serves this model in exactly one place — a standard-medical-deduction scenario whose flipped per-case parameters, paired-bootstrap intervals, and level gate ship in an export pinned to the exact model file by hash, with the seven jurisdictions outside the [0.7, 1.4] factor-adjusted level-ratio range disabled — and no simulation result in this paper uses model draws.</p>
<div id="tbl-validate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-validate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Fiscal 2024 state-level calibration of predicted official-error rates, matched frozen-model comparisons. Factors are fit on out-of-sample fiscal 2023 predictions and frozen before touching fiscal 2024.
</figcaption>
<div aria-describedby="tbl-validate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Unfactored (frozen model)</th>
<th style="text-align: right;">With frozen FY2023 factors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>State MAE, equal-weighted</td>
<td style="text-align: right;">1.73pp</td>
<td style="text-align: right;">0.875pp</td>
</tr>
<tr class="even">
<td>State MAE, issuance-weighted</td>
<td style="text-align: right;">1.57pp</td>
<td style="text-align: right;">0.808pp</td>
</tr>
<tr class="odd">
<td>Cross-state correlation (equal-weighted)</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.91</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>State-level calibration uses a strictly temporal protocol: models fit through 2022 predict 2023 out of sample; state observed-to-predicted ratios, shrunk toward one by an empirical-Bayes precision rule <span class="math inline">\(\tilde{f}_s = 1 + (f_s - 1)\,\tau^2/(\tau^2 + v_s)\)</span>, with <span class="math inline">\(v_s\)</span> the delta-method ratio variance on Kish effective sample size, are frozen and applied to fiscal 2024. Most cross-state alignment comes from the factors, whose interpretation — administration, omitted policy, model error — the data do not identify.</p>
<p><strong>Policy contrasts are descriptive.</strong> Under an event definition requiring a medical finding with payment impact, elderly/disabled claimants in states <em>without</em> a standard medical deduction — where itemized documentation is required — show a 2.60% medical-event rate, against 2.97% in a mixed comparison cell (standard-deduction-state claimants pooled with below-floor claimants everywhere); the cross section runs <em>against</em> a simple burden-increases-error reading, and adoption is endogenous. Calendar-aligned adoption contrasts against never-adopting states are small and mixed — Arizona +2.07 points claimant-conditioned but +0.64 on the stable all-elderly/disabled denominator; Kentucky −0.42 claimant-conditioned; California +0.11 claimant-conditioned but −1.40 on the stable denominator; Louisiana and Michigan within 0.2 points of zero, though those two adopters have zero treated-period events in the windows, so their contrasts are control-trend arithmetic only — with single-digit event counts throughout. Two cautions transfer beyond this paper: an earlier pipeline’s dramatic Kentucky estimate (−5.3 points) dissolved under a corrected event definition and calendar windows; and standard-medical-deduction adoption is typically bundled with utility-allowance offsets for cost neutrality, so these are contrasts of policy bundles. Causal identification awaits engine-computed counterfactuals (<a href="#sec-roadmap" class="quarto-xref">Section&nbsp;8</a>).</p>
<p>Three further feature families enter every model stage as seventeen case-level features: certification timing (months since certification and period length from the file’s <code>LASTCERT</code> and <code>CERTMTH</code>, a final-two-months indicator, and its interaction with elderly/disabled composition), state broad-based categorical eligibility from the FNS State Options Reports (44 adopting agencies in fiscal 2024, mapped to each training year’s report edition; the file’s own <code>CAT_ELIG</code> is excluded because its codes conflate BBCE with traditional categorical eligibility), and Medicare Part B premium bands — reconstructing gross medical expense as the file’s excess amount plus the $35 deduction floor and comparing it with the sampled month’s published premium. Their marginal contribution, holding the protocol fixed: classifier ROC AUC 0.7666 to 0.7679, hurdle stage-1 AUC 0.8356 to 0.8397, equal-state calibration MAE 1.83 to 1.71 percentage points, distributional coverage’s mean absolute gap 4.38 to 4.64 points (worse). The band construction validates exactly where it should: all 36 elderly Colorado cases censored at the state’s $165 standard medical deduction map, after the floor reconstruction, to $200 gross — inside the just-above-premium band — where a naive comparison on the excess scale misclassifies six of them.</p>
</section>
<section id="sec-simulate" class="level2">
<h2 class="anchored" data-anchor-id="sec-simulate">Simulating measured rates under cost sharing</h2>
<p>The public simulator resamples each state’s own sampled cases with replacement at the realized or a hypothetical sample size and recomputes the weighted error rate <span class="citation" data-cites="efron1979bootstrap">(<a href="#ref-efron1979bootstrap" role="doc-biblioref">Efron 1979</a>)</span>, centered on the official rate. The error definition is the official one — adjudicated status with the recorded amount above the threshold. Three findings, all on fiscal 2024 data, all inheriting the file’s truncation of ineligible-case error (which understates the variability shown) and an i.i.d. approximation to each state’s actual sampling design; the official rate’s federal re-review adjustment enters only as a fixed level. That fixed layer deserves a number: the gap between each state’s official fiscal 2024 rate and the rate computable from its public file — federal re-review integration plus the ineligible-case error the file never records — is a median 31% of the official rate across jurisdictions, ranging from −3% (the adjustment can run downward: Minnesota and Nevada) to 44% for New York and 81% for Alaska. Anchoring keeps the level right, but the layer contributes no sampling variance to the draws and no scenario in this paper reaches it; the deployed simulator now discloses each state’s own file-covered share alongside its results. A committed registry decomposes the wedge by the published components: nationally, the official 10.93% fiscal 2024 rate is a 7.22% file-computable rate (5.73 overpayment plus 1.49 underpayment) plus a 3.71-point wedge, and 3.53 of those points — 95% — sit in the overpayment component, with twenty states’ underpayment wedges running negative. That concentration is consistent with the excluded ineligible-case error, which is overpayment by construction, dominating the layer — though the publications do not separately identify it from the federal re-review integration, so the split stays an accounting decomposition rather than an attribution. All figures quote the committed simulation artifact.</p>
<p><strong>Tier assignment approaches a coin flip for boundary states</strong> (<a href="#fig-co" class="quarto-xref">Figure&nbsp;1</a>, <a href="#tbl-boundary" class="quarto-xref">Table&nbsp;5</a>). With no policy change at all, the probability that a fresh QC-style sample lands in a different cost-share tier than the official point rate implies is 46–50% for the five states nearest boundaries.</p>
<div id="fig-co" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-co-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="figures/co_measured_rate.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Colorado’s simulated measured-rate distribution (100,000 resampled QC-style measurements, official error definition, centered on the official 9.97% rate) against the cost-share tier bands. The state’s official rate sits 0.03 points below the 15%-share boundary; 52% of simulated measurements fall below it and 48% above. Generated by the committed paper/generate_figures.py (seed 11)."><img src="figures/co_measured_rate.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-co-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Colorado’s simulated measured-rate distribution (100,000 resampled QC-style measurements, official error definition, centered on the official 9.97% rate) against the cost-share tier bands. The state’s official rate sits 0.03 points below the 15%-share boundary; 52% of simulated measurements fall below it and 48% above. Generated by the committed <code>paper/generate_figures.py</code> (seed 11).
</figcaption>
</figure>
</div>
<p>The formula maps a point estimate to a tier with no adjustment for sampling uncertainty; near a boundary, tier assignment turns as much on the sampling draw as on the underlying rate. This is the accountability-measurement problem documented for school accountability ratings <span class="citation" data-cites="kane2002volatility">(<a href="#ref-kane2002volatility" role="doc-biblioref">Kane and Staiger 2002</a>)</span>, now carrying direct fiscal prices.</p>
<div id="tbl-boundary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-boundary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Boundary states under the fiscal 2028 tier schedule applied to fiscal 2024 issuance — an illustration of stakes, not a forecast. Colorado’s step from the 10% to the 15% tier is $63.4M per year.
</figcaption>
<div aria-describedby="tbl-boundary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>State</th>
<th style="text-align: right;">Official rate</th>
<th style="text-align: right;">P(different tier)</th>
<th style="text-align: right;">Expected annual cost share</th>
<th style="text-align: right;">SD of the bill</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>North Dakota</td>
<td style="text-align: right;">7.91%</td>
<td style="text-align: right;">50%</td>
<td style="text-align: right;">$7.9M</td>
<td style="text-align: right;">$3.5M</td>
</tr>
<tr class="even">
<td>Washington</td>
<td style="text-align: right;">6.06%</td>
<td style="text-align: right;">48%</td>
<td style="text-align: right;">$50.2M</td>
<td style="text-align: right;">$48.5M</td>
</tr>
<tr class="odd">
<td>Colorado</td>
<td style="text-align: right;">9.97%</td>
<td style="text-align: right;">49%</td>
<td style="text-align: right;">$156.4M</td>
<td style="text-align: right;">$32.8M</td>
</tr>
<tr class="even">
<td>Kansas</td>
<td style="text-align: right;">9.98%</td>
<td style="text-align: right;">47%</td>
<td style="text-align: right;">$46.9M</td>
<td style="text-align: right;">$9.5M</td>
</tr>
<tr class="odd">
<td>Nevada</td>
<td style="text-align: right;">5.94%</td>
<td style="text-align: right;">46%</td>
<td style="text-align: right;">$23.7M</td>
<td style="text-align: right;">$26.0M</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Audit volume is a two-sided instrument.</strong> Increasing the QC sample shrinks sampling variance around the state’s underlying rate, holding the error process fixed (<a href="#sec-limitations" class="quarto-xref">Section&nbsp;9</a>; the corrective-feedback channel from reviewing more cases is not modeled, and these figures are gross of review costs — which rose for states when OBBBA cut the federal administrative match from 50 to 25% beginning fiscal 2027). In expectation, 500 additional reviews save money for states just below a boundary — Missouri +$3.9M, Tennessee +$3.7M, Indiana +$3.3M annually — and cost money for states just above one, for whom the chance of a below-boundary draw had positive expected value: California −$30.3M, Pennsylvania −$13.1M, Texas −$13.1M. Added volume almost always reduces the standard deviation of the annual bill (California by $44M), so risk-averse states may rationally buy audits against their expectation. The formula thus embeds an asymmetry: expected cost share falls with additional sample volume for states just below a boundary and rises for states just above one — a property worth reading alongside the no-dispute election of <a href="#sec-qc" class="quarto-xref">Section&nbsp;3</a>.</p>
<p><strong>Category-suppression bounds are large.</strong> Removing 50% (100%) of the observed error dollars attached to the finding elements that four policy options standardize — the standard medical deduction, standard self-employment deduction, heat-and-eat utility standardization, and broad-based categorical eligibility resource exemptions — corresponds to roughly $609M ($1,310M) per year nationally in expected cost share. These are accounting bounds, not causal estimates: they hold the error process fixed and answer “what if these categories’ observed error dollars shrank,” an upper-bound identity rather than a behavioral prediction — the descriptive adoption contrasts of <a href="#sec-model" class="quarto-xref">Section&nbsp;6</a> are the reason for the caution. They speak only to measured error and cost share; the options themselves change benefit amounts, eligibility, and program cost, none of which is modeled here. Two further scope notes: OBBBA itself narrowed the heat-and-eat channel, restricting the LIHEAP-triggered utility allowance to households with an elderly or disabled member (§ 10103), so that lever’s fiscal 2024 error mix overstates its remaining reach; and the expected cost-share effect of a marginal error reduction is near zero for states deep within a tier (New York at 14.09%, Alaska at 24.66%) and largest near boundaries.</p>
<section id="sec-fy2025" class="level3">
<h3 class="anchored" data-anchor-id="sec-fy2025">The realized fiscal 2025 rates</h3>
<p>The simulation’s claim — that tier assignment at current sample sizes is substantially a draw from sampling noise — is built from fiscal 2024 microdata alone. On June 24, 2026, the renamed agency published the fiscal 2025 rates <span class="citation" data-cites="fna2025per">(<a href="#ref-fna2025per" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Administration 2026</a>)</span>; this repository postdates that publication, so what follows is a check of input independence, not a registered forecast — the fiscal 2025 rates enter the analysis only as the realized outcomes being classified, and the noise scale that classifies them uses no fiscal 2025 information. Eighteen of 53 jurisdictions changed cost-sharing tiers. Whether any single change reflects program performance is exactly the question sampling error poses: under the committed simulator’s FY2024 sampling standard deviations, with both years carrying independent noise of equal scale, a year-over-year move is distinguishable from noise at 95% confidence only beyond 2.77 of a single year’s standard deviations. Ten jurisdictions cleared that bar (Delaware, Florida, Hawaii, Illinois, Kentucky, Minnesota, North Carolina, New Jersey, Ohio, and West Virginia) — but only seven of those ten changed tiers, so 11 of the 18 tier changes sit inside the noise band; the median jurisdiction moved 1.38 standard deviations. Movement figures come from the committed movement artifact (deterministic, seed 11; <a href="#sec-availability" class="quarto-xref">Section&nbsp;11</a>); tier-step and election dollars come from the deployed simulator’s committed inputs and its election engine, and price shares at fiscal 2024 issuance levels — no caseload or allotment growth to the billed year is projected.</p>
<p>The two tails of that distribution make the point more sharply than the counts. Colorado moved from 9.97% to 10.09% — 0.12 percentage points, 0.13 standard deviations, indistinguishable from re-measuring the same program — and that move crossed the 10% boundary into the 15% tier, repricing its FY2028 exposure by roughly $63M a year at fiscal 2024 issuance levels. Real movement exists alongside it: Hawaii went from 6.68% to 10.92% (11.2 standard deviations, two tiers up), New Jersey from 14.33% to 6.86% (−11.2, from the top tier to the 5% tier), Kentucky from 9.11% to 4.70% (−7.2, into the 0% tier). The formula cannot tell these apart; it prices Colorado’s noise and New Jersey’s real movement — whatever mix of program change and review practice produced it — with the same schedule. The national rate fell from 10.93% to 10.62%.</p>
<p>The realized year also calibrates how much true year-over-year process movement the sampling-only simulator omits. Across states, the variance of the one-year change decomposes as twice the mean squared sampling standard deviation plus a process-drift variance <span class="math inline">\(\tau^2\)</span>; the method-of-moments estimate is <span class="math inline">\(\tau = 1.62\)</span> percentage points (95% CI 0.81–2.25 from a paired bootstrap over jurisdiction movement–SD rows), and a median/MAD version robust to the large realized moves gives <span class="math inline">\(\tau = 1.07\)</span> (CI 0–1.74). Process drift on this transition is likely real — the classical interval excludes zero; the robust one does not — and comparable in scale to sampling noise for a typical state, though a single transition cannot separate program drift from any change in QC design or practice between the two years. The simulator’s draws remain sampling-only — a disclosed lower bound on total year-over-year uncertainty — with the drift estimate carried as a candidate calibration rather than silently added.</p>
<p>Churn reaches the delay clause too. Had fiscal 2024 rates carried the delay test, ten jurisdictions would have met it; at fiscal 2025 — the first year the test binds — seven do. Florida, Massachusetts, Maryland, New Jersey, and New York left that hypothetical roster and Delaware and Illinois joined it: the assignment that zeroes a state’s FY2028 bill churns under the same measurement noise that moves tiers.</p>
<p>The fiscal 2025 publication also started the clock the statute set: the FY2028 share keys to each state’s fiscal 2025 or fiscal 2026 rate, at its election, and fiscal 2026 closes September 30, 2026. The deployed simulator now prices that election — for Colorado, a 52.5% probability that a QC-sized fiscal 2026 measurement lands below the locked 10.09% rate, worth about $31M a year in expectation from the election alone; the dollars come from the near-even odds the measurement lands below the 10% tier <em>boundary</em>, repricing the $63.4M step — and models the delay clause as it binds: delayed years enter expected bills as zero, and a fiscal 2026 draw that crosses 13.33% pushes the start to FY2030, zeroing FY2029 as well.</p>
<p>The same clock defines what can still be registered. Fiscal 2026 is the first measurement year the statute exposes end to end — it opened after the July 4, 2025 enactment (per the GPO record for Public Law 119-21, as the registration documents) and closes September 30, 2026 — and no official fiscal 2026 rate yet exists. The repository therefore now carries a pre-registration for them: the disclosure above (a check of input independence, not a registered forecast) holds for fiscal 2025, and the fiscal 2026 design closes that gap prospectively. <code>analysis/PREREGISTRATION_OBBBA_BOUNDARY.md</code> commits the boundary quasi-experiment in advance — running-variable windows at the 6/8/10 tier cuts and the 13.33% delay test, estimators and decision rules fixed to seeds, per-state no-response null predictions from this same observed-resample engine, the outcome list (measured rates, the sampling-plan election that carries the precision waiver, cause-mix shifts), and falsification tests, one of which — the fiscal 2024 pre-period placebo — is executed and locked at registration — with the machine-readable predictions SHA-256-pinned and their regeneration byte-locked in CI. The public commit history is the registration record and the registering pull request’s merge is the registration event: whatever fiscal 2026 shows, the analyses this repository will run on it were fixed while the year was still in the field, before its official outcomes exist, and anything beyond them will be labeled post hoc.</p>
</section>
<section id="sec-adoption" class="level3">
<h3 class="anchored" data-anchor-id="sec-adoption">Pricing engine adoption through the formula</h3>
<p>The decomposition of <a href="#sec-decompose" class="quarto-xref">Section&nbsp;5</a> says what share of error dollars the computing apparatus carries; the cost-sharing formula decides what those shares mean in billed dollars. The deployed simulator composes the two: for each jurisdiction, zero the error dollars of every case whose recorded cause slots include a computing-apparatus code, shift the anchor down by the file-rate reduction those removals produce, and reprice the fiscal 2026 election and delay machinery on the adjusted draws. Cause coding exists for all 53 jurisdictions; engine verification covers seven, so in the other 46 the scenario prices the file’s own coding, not a verified computation. The anchor convention is additive by design: the official rate exceeds the file-computable rate by a layer of federal re-review integration and ineligible-case error this simulator treats as a fixed level everywhere (<a href="#sec-limitations" class="quarto-xref">Section&nbsp;9</a>), and the cause coding says nothing about that layer’s composition — so the removed dollars lower the anchor by exactly the percentage points they remove from the file rate, never scaled onto the adjustment. The fiscal 2025 rate stays locked history — adoption enters only through the simulated fiscal 2026 measurement, which is the counterfactual’s shape: a state adopting now changes the year being measured, not the year already published. The per-case class flags are committed with the artifact and reconcile exactly (at <span class="math inline">\(10^{-9}\)</span>, on the unrounded weight path) with the cause-share values behind <a href="#tbl-decompose" class="quarto-xref">Table&nbsp;3</a>, with the serialization difference of the published rounded arrays bounded at <span class="math inline">\(2 \times 10^{-6}\)</span> and the case ordering locked to those arrays by test; an independent Python mirror of the browser engine, down to its random-number stream, reproduces every figure quoted below. The strict and broad classes are two accounting scenarios under nested cause-code sets, not bounds: because billing is not monotone in error reduction, an intermediate convention need not land between them. Neither is a causal adoption estimate — cause codes are reviewer judgments, the broad class includes policy misapplication an engine removes only where it drives the determination end to end, and the fiscal 2024 cause mix is assumed for fiscal 2026.</p>
<p>Summed over all 53 jurisdictions, expected FY2028 bills move from $7.67B a year to $7.57B under the strict scenario and $6.94B under the broad one. The strict class carries $232M a year in error dollars (<a href="#tbl-decompose" class="quarto-xref">Table&nbsp;3</a>) but moves expected bills by only about $97M: the schedule prices tiers, not points, and a rate reduction that crosses no boundary bills identically. Colorado, measured 0.09 points above the 10% boundary, is the opposite case — the strict removals move its simulated center to 9.54% and the broad ones to 9.30%, reducing its expected FY2028 bill by $16M to $23M a year from a $159M baseline, with the election-win probability rising from 52% to 74–82%.</p>
<p>The formula does not price error reduction monotonically, and the delay clause is why. New York, at 13.18%, sits just under the 13.33% threshold: at baseline, 42% of simulated fiscal 2026 measurements cross it and defer the first bill, holding the expected FY2028 bill to $630M against a $1.08B locked tier value. The broad scenario moves New York’s center to 11.81% — still the 15% tier — and cuts the deferral odds to 5%: the expected FY2028 bill <em>rises</em> to $1.02B. Georgia, at 15.21%, shows the same mechanics from above the threshold: 98% of baseline draws defer again (expected FY2029 bill $9M), while the bounds cut deferral to 86% and 15% and raise the expected FY2029 bill to $63M and $396M. Within the simulator’s FY2028–29 horizon a deferred bill prices as zero, because it keys to fiscal 2027, a year the simulation does not draw — deferral is not forgiveness, and the horizon accounting is disclosed rather than netted. New York’s strict share is exactly zero — its file codes no strict-class dollars — so its strict scenario equals its baseline. The construct differs in kind from the retired accounting levers of <a href="#sec-roadmap" class="quarto-xref">Section&nbsp;8</a>: those subtracted finding-category dollars to stand in for a policy option’s behavioral effect, and a real case showed the substitution reversing the model’s sign; here the subtraction is the question itself — what the file’s own coding assigns to the apparatus a verified engine replaces.</p>
</section>
<section id="sec-fy2027" class="level3">
<h3 class="anchored" data-anchor-id="sec-fy2027">The fiscal 2027 measurement year</h3>
<p>Fiscal 2027 is the first measurement year still open to policy and sampling-plan choices — it sets the FY2030 bill, and sampling-plan changes go to the regional office before the review period begins. It is also the first year the 2025 reconciliation act’s parameter changes bind the QC arithmetic: Public Law 119-21 §10101 moves maximum-allotment indexing to June-to-June CPI-U with amended household-size factors, which projects the 48-state four-person maximum to $1,029 (an estimate until the June 2026 index publishes), and the QC tolerance threshold projects to $59 by the unique floor convention that reproduces every published threshold since fiscal 2022 (hardening when USDA publishes the June 2026 food-plan cost).</p>
<p>The deployed simulator prices that year for the seven verified states by repricing their fiscal 2024 cases under fiscal 2026 and 2027 parameters and forward composition — case weights recalibrated to administrative actuals and forward enrollment margins (all required calibration gates pass; four clipped targets are disclosed in the committed summary) — with the repricing authorized by a self-oracle gate: before any parameter changes, the pipeline must reproduce the file’s own formula benefit exactly, which it does for all 6,081 replayable cases. The repriced rate is then re-anchored at the official fiscal 2025 level, the same discipline the simulator uses everywhere.</p>
<p>What repricing cannot decide is a convention: each case’s recorded deviation must be carried from observed to repriced parameters, and fixed-dollars and proportional-to-benefit are both defensible. The two conventions place each verified state’s anchored fiscal 2027 mechanical rate 1.8 to 3.8 percentage points apart (fiscal 2026: 0.9 to 1.8) — comparable to or wider than a five-point-share tier’s 2-point rate width, so the choice of an accounting convention can move a state’s projected tier by itself. The band, not either endpoint, is the projection this method supports, and neither endpoint is a behavioral forecast: the gap is displayed in the simulator as a range and committed with the per-state values. States without verified encodings get the parameter inputs and no projection: a repriced rate without a verified computation would be an unsupported number, so none is shown.</p>
</section>
<section id="sec-events" class="level3">
<h3 class="anchored" data-anchor-id="sec-events">System replacements in the record: event studies</h3>
<p>The accounting scenarios of <a href="#sec-adoption" class="quarto-xref">Section&nbsp;7.2</a> price a cause class; whether that class moves when the computing apparatus actually changes is a causal question, and a companion paper answers it as far as the record allows <span class="citation" data-cites="ghenis2026migrations">(<a href="#ref-ghenis2026migrations" role="doc-biblioref">Ghenis 2026</a>)</span>. Three state eligibility-system replacements — Rhode Island’s UHIP (September 2016), Kentucky’s Benefind (February 2016), and Oregon’s ONE expansion (February 2021) — are estimated there against synthetic controls drawn from states with no migration in a public event registry, with permutation inference and decision rules frozen before estimation. Rhode Island earns the frozen rule’s <code>signal</code>: strict computing-apparatus error dollars rise $2.90 per weighted case-month against the synthetic donor (p = 0.023) while the client-caused placebo does not fire, and the rise concentrates in fiscal 2017–19, a pre-named window inside the interval for which the Food and Nutrition Service later billed the state $37.3 million — a descriptive, verdict-inert check. Kentucky and Oregon return <code>no_protocol_defined_signal</code>, Oregon’s a refusal because its placebo fires inside the pandemic window. A second frozen protocol decomposes the Rhode Island result by cause code and finds the rise in computer-generated mass-change error under both a joint-fit and a fixed-donor estimator, with the design’s placebo dependence on the shared donor fit reported beside the result.</p>
<p>The estimand throughout is a bundled system replacement as implemented — staffing, process, and software together — never “the effect of a rules engine.” The connection to <a href="#sec-adoption" class="quarto-xref">Section&nbsp;7.2</a> is narrow: the cause class those scenarios price by accounting convention is the class that rose after Rhode Island’s migration. Neither result checks the other. Protocols, artifacts, and both referee rounds are committed (analysis/RIKY_EVENT_STUDY_PROTOCOL.md; analysis/UHIP_DECOMPOSITION_PROTOCOL.md; analysis/FIXED_DONOR_PROTOCOL.md; paper-causal/).</p>
</section>
</section>
<section id="sec-roadmap" class="level2">
<h2 class="anchored" data-anchor-id="sec-roadmap">Toward engine-computed counterfactuals</h2>
<p>The counterfactual gap has begun to close. For one state and one option — Colorado and the standard medical deduction — the pieces now run end to end, and the run itself produced findings. The first is structural: the certified parity chain never consumes Colorado’s standard-medical-deduction rule, because QC editing bakes the deduction into the stored expense fields and the federal computation path reproduces every case exactly without it — a sharper instance of the Minimodel-canon scope point of <a href="#sec-oracle-scope" class="quarto-xref">Section&nbsp;4.1</a>. (A separate raw-facts leg, reconstructing inputs rather than supplying the file’s intermediates, agrees on 845 of 856 cases, its eleven divergences diagnosed to missing public TANF facts and one utility-allowance tier conflict; only the supplied-intermediates certified chain is exact.) A simulation-only composition adapter that binds the state rule into the federal path, validated by exact baseline invariance on all 856 cases, reprices the option’s removal only as bounds, because the public file censors 46 medical-expense records at exactly $165: between −$1.46 and $0 per case-month. The second is a sign disagreement: feeding the engine-recomputed intermediates through the error model’s direct crossing classifier, applied as a level shift, implies a cost-share change of −$1.55M to −$2.20M per year for removing the deduction. That figure is a range across the three censoring variants, not a confidence interval; the paired-bootstrap intervals are wider — the point variant’s is [−$4.1M, +$0.3M] — and span zero in two of the three. The accounting-reverse bound for the same flip is +$7.1M, and the robust form of the disagreement survives the intervals: all three exclude it, with a maximum upper bound of +$0.6M. Neither sign is validated — the artifact itself warns that the fitted models implying lower error without the deduction is not evidence that documentation requirements reduce errors. The argument for retiring the accounting levers from the public simulator is accordingly not that the model is right but that the two mechanisms answer different questions — one is an upper-bound identity scaling observed error dollars by finding category, the other a model-implied association of re-adjudication risk with the flipped feature — and their divergence on a real case shows the substitution was never innocuous. The simulator now serves only the model scenario as a policy lever, level-gated and labeled as an association; the engine-adoption scenarios of <a href="#sec-adoption" class="quarto-xref">Section&nbsp;7.2</a> are accounting constructs by design, kept because there the computing-apparatus classes are the question rather than a proxy for a behavioral response. What remains open is breadth: engine legs for the remaining options (self-employment is not identified from public data, which records net rather than gross income) and the other verified states, feeding the harness raw facts instead of file-derived intermediates (<a href="#sec-oracle-scope" class="quarto-xref">Section&nbsp;4.1</a>), and the cost-sharing formula itself as an encodable target: the sampling formulas of 7 C.F.R. § 275.11(b) and the tier schedule of 7 U.S.C. § 2013(a)(2), with its election and delay clauses, can be encoded and tested at their published boundary values, replacing hand-transcribed constants in simulators like this one.</p>
</section>
<section id="sec-limitations" class="level2">
<h2 class="anchored" data-anchor-id="sec-limitations">Limitations</h2>
<p>The parity result certifies agreement with the edited file’s Minimodel-computed chain from supplied intermediates — not independent derivation from raw facts, and not the reviewer-adjudicated outcome fields (<a href="#sec-oracle-scope" class="quarto-xref">Section&nbsp;4.1</a>); it is also post-correction on the same case set, pending a fiscal 2025 confirmatory run. The public file excludes ineligible-case and full-overissuance error, truncating the error distribution every file-based estimate inherits. The replay decomposition depends on a reconstruction solver whose filters exclude 22 of 305 error cases, and its residual class is an upper bound in case shares, not dollar shares. The error models predict an adjudicated, thresholded label — a property of the measurement system, with a documented manipulation history (<a href="#sec-qc" class="quarto-xref">Section&nbsp;3</a>). Cross-state model transport is imperfect: the model’s raw level underpredicts high-error states, all nine coverage gaps remain one-sided negative after the tail and level-factor fixes — and after the committed location repair, which improves every level but closes only part of the gap — and the deployed simulator accordingly serves the model only for its level-gated standard-medical-deduction scenario, with seven jurisdictions disabled outright; every simulation result in this paper uses the observed-resample engine. That mode resamples i.i.d. from a probability sample whose actual design varies by state, treats the official rate’s federal re-review adjustment as a fixed level with no variance contribution, and holds the error process fixed — no behavioral response of agencies or households to cost sharing, no corrective-feedback channel from audit volume, both live questions the fiscal 2025–27 files will begin to answer under the new incentives. Adoption contrasts are descriptive contrasts of policy bundles; nothing here identifies causal effects of burden policies on error.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>A measurement system designed for oversight now sets prices. That makes the QC files three things at once: a case-level verification oracle against the agency’s own computational canon — where the bar can be exact, and holding it exact is what made the residuals informative; the dataset showing that most measured error among eligible cases is information failure rather than calculation failure; and a sampling frame whose noise the new formula converts into near-even-odds tier assignment for boundary states. The modeling bar cannot be exact, and this paper went through six rounds of adversarial review, archived unedited in the repository. The system this points toward is one in which the rules that compute benefits, the requirements they impose on households, and the errors they produce are executable, testable, and priced from the same verified source.</p>
</section>
<section id="sec-availability" class="level2">
<h2 class="anchored" data-anchor-id="sec-availability">Data and code availability</h2>
<p>The repository <code>PolicyEngine/snap-qc-sim</code> contains the analysis pipeline (deterministic; independent clean-clone reruns reproduce all five pipeline artifacts byte-for-byte on the pinned interpreter version, recorded in <code>.python-version</code> and each artifact’s provenance block), the simulator, frozen simulation, decomposition, and certification artifacts under <code>paper/snapshot/</code> (including the complete per-case replay output, the layer-1 and layer-2 classification outputs, and the reconstruction scripts), the archived adversarial review reports — six rounds — and the round-1 editorial synthesis under <code>paper/reviews/</code>, the fact catalog (<code>paper/FACTS.md</code>), the fiscal 2026 pre-registration (<code>analysis/PREREGISTRATION_OBBBA_BOUNDARY.md</code>, with its hash-pinned predictions artifact and deterministic generator), and this manuscript. The verification harness and per-case suite reports are public in <code>TheAxiomFoundation/axiom-oracles</code>; the encodings in <code>TheAxiomFoundation/rulespec-us</code>; the engine in <code>TheAxiomFoundation/axiom-rules-engine</code>. QC public-use files are available from USDA FNS <span class="citation" data-cites="fns2024techdoc">(<a href="#ref-fns2024techdoc" role="doc-biblioref">U.S. Department of Agriculture, Food and Nutrition Service 2025b</a>)</span>, and the training files are tracked in the public <span class="citation" data-cites="giannella_snapqc">Giannella and Molin (<a href="#ref-giannella_snapqc" role="doc-biblioref">2026</a>)</span> repository. Reproduction commands are in the repository README.</p>
</section>
<section id="disclosure" class="level2">
<h2 class="anchored" data-anchor-id="disclosure">Disclosure</h2>
<p>The author leads PolicyEngine, which builds the simulator described here, and The Axiom Foundation, which builds the rulespec-us encodings and the axiom-oracles verification harness whose parity this paper reports — the paper is an evaluation of systems its author is responsible for. The mitigations are structural: every parity claim replays against the government’s own recorded values at zero tolerance from committed, hash-pinned artifacts any reader can rerun, and the manuscript’s six rounds of adversarial review are archived unedited in the repository.</p>
</section>
<section id="acknowledgments" class="level2">
<h2 class="anchored" data-anchor-id="acknowledgments">Acknowledgments</h2>
<p>I thank Eric Giannella and Ben Molin for the open reconstruction and registry code this work builds on. All errors are my own.</p>

</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-abadie2021using" class="csl-entry" role="listitem">
Abadie, Alberto. 2021. <span>“Using Synthetic Controls: Feasibility, Data Requirements, and Methodological Aspects.”</span> <em>Journal of Economic Literature</em> 59 (2): 391–425.
</div>
<div id="ref-abadie2010synthetic" class="csl-entry" role="listitem">
Abadie, Alberto, Alexis Diamond, and Jens Hainmueller. 2010. <span>“Synthetic Control Methods for Comparative Case Studies: Estimating the Effect of <span>California</span>’s Tobacco Control Program.”</span> <em>Journal of the American Statistical Association</em> 105 (490): 493–505.
</div>
<div id="ref-chernozhukov2010rearrange" class="csl-entry" role="listitem">
Chernozhukov, Victor, Iván Fernández-Val, and Alfred Galichon. 2010. <span>“Quantile and Probability Curves Without Crossing.”</span> <em>Econometrica</em> 78 (3): 1093–125. <a href="https://doi.org/10.3982/ECTA7880">https://doi.org/10.3982/ECTA7880</a>.
</div>
<div id="ref-crs2018errors" class="csl-entry" role="listitem">
Congressional Research Service. 2018. <em>Errors and Fraud in the Supplemental Nutrition Assistance Program (SNAP)</em>. No. R45147. <a href="https://www.congress.gov/crs_external_products/R/PDF/R45147/R45147.4.pdf">https://www.congress.gov/crs_external_products/R/PDF/R45147/R45147.4.pdf</a>.
</div>
<div id="ref-dellavigna2020forecasting" class="csl-entry" role="listitem">
DellaVigna, Stefano, Nicholas Otis, and Eva Vivalt. 2020. <span>“Forecasting the Results of Experiments: Piloting an Elicitation Strategy.”</span> <em>AEA Papers and Proceedings</em> 110: 75–79. <a href="https://doi.org/10.1257/pandp.20201080">https://doi.org/10.1257/pandp.20201080</a>.
</div>
<div id="ref-dellavigna2018predicting" class="csl-entry" role="listitem">
DellaVigna, Stefano, and Devin Pope. 2018. <span>“Predicting Experimental Results: Who Knows What?”</span> <em>Journal of Political Economy</em> 126 (6): 2410–56.
</div>
<div id="ref-duan1983smearing" class="csl-entry" role="listitem">
Duan, Naihua. 1983. <span>“Smearing Estimate: A Nonparametric Retransformation Method.”</span> <em>Journal of the American Statistical Association</em> 78 (383): 605–10. <a href="https://doi.org/10.1080/01621459.1983.10478017">https://doi.org/10.1080/01621459.1983.10478017</a>.
</div>
<div id="ref-efron1979bootstrap" class="csl-entry" role="listitem">
Efron, Bradley. 1979. <span>“Bootstrap Methods: Another Look at the Jackknife.”</span> <em>The Annals of Statistics</em> 7 (1): 1–26. <a href="https://doi.org/10.1214/aos/1176344552">https://doi.org/10.1214/aos/1176344552</a>.
</div>
<div id="ref-ghenis2026migrations" class="csl-entry" role="listitem">
Ghenis, Max. 2026. <span>“What a System Replacement Does to Measured Error: Three <span>SNAP</span> Eligibility-System Migrations in the Quality-Control Record.”</span> <a href="https://policyengine.org/us/snap-payment-error-simulator/paper-migrations">https://policyengine.org/us/snap-payment-error-simulator/paper-migrations</a>.
</div>
<div id="ref-giannella_snapqc" class="csl-entry" role="listitem">
Giannella, Eric, and Ben Molin. 2026. <em>Snap_qc: Reconstruction and Analysis Code for the SNAP Quality Control Public-Use Files</em>. <a href="https://github.com/giannella/snap_qc">https://github.com/giannella/snap_qc</a>.
</div>
<div id="ref-herd2018burden" class="csl-entry" role="listitem">
Herd, Pamela, and Donald P. Moynihan. 2018. <em>Administrative Burden: Policymaking by Other Means</em>. Russell Sage Foundation.
</div>
<div id="ref-homonoff2021recertification" class="csl-entry" role="listitem">
Homonoff, Tatiana, and Jason Somerville. 2021. <span>“Program Recertification Costs: Evidence from <span>SNAP</span>.”</span> <em>American Economic Journal: Economic Policy</em> 13 (4): 271–98.
</div>
<div id="ref-kane2002volatility" class="csl-entry" role="listitem">
Kane, Thomas J., and Douglas O. Staiger. 2002. <span>“The Promise and Pitfalls of Using Imprecise School Accountability Measures.”</span> <em>Journal of Economic Perspectives</em> 16 (4): 91–114. <a href="https://doi.org/10.1257/089533002320950993">https://doi.org/10.1257/089533002320950993</a>.
</div>
<div id="ref-koenker1978quantile" class="csl-entry" role="listitem">
Koenker, Roger, and Gilbert Bassett. 1978. <span>“Regression Quantiles.”</span> <em>Econometrica</em> 46 (1): 33–50. <a href="https://doi.org/10.2307/1913643">https://doi.org/10.2307/1913643</a>.
</div>
<div id="ref-merigoux2021catala" class="csl-entry" role="listitem">
Mérigoux, Denis, Nicolas Chataing, and Jonathan Protzenko. 2021. <span>“Catala: A Programming Language for the Law.”</span> <em>Proceedings of the ACM on Programming Languages</em> 5 (ICFP): 1–29. <a href="https://doi.org/10.1145/3473582">https://doi.org/10.1145/3473582</a>.
</div>
<div id="ref-merigoux2021compiler" class="csl-entry" role="listitem">
Mérigoux, Denis, Raphaël Monat, and Jonathan Protzenko. 2021. <span>“A Modern Compiler for the <span>French</span> Tax Code.”</span> <em>Proceedings of the 30th ACM SIGPLAN International Conference on Compiler Construction (CC ’21)</em>, 71–82. <a href="https://doi.org/10.1145/3446804.3446850">https://doi.org/10.1145/3446804.3446850</a>.
</div>
<div id="ref-oecd2020cracking" class="csl-entry" role="listitem">
Mohun, James, and Alex Roberts. 2020. <em>Cracking the Code: Rulemaking for Humans and Machines</em>. OECD Working Papers on Public Governance No. 42. OECD Observatory of Public Sector Innovation. <a href="https://doi.org/10.1787/3afe6ba5-en">https://doi.org/10.1787/3afe6ba5-en</a>.
</div>
<div id="ref-nrc1987rethinking" class="csl-entry" role="listitem">
National Research Council. 1987. <em>Rethinking Quality Control: A New System for the <span>Food Stamp Program</span></em>. National Academies Press. <a href="https://nap.nationalacademies.org/catalog/18900/">https://nap.nationalacademies.org/catalog/18900/</a>.
</div>
<div id="ref-pedregosa2011sklearn" class="csl-entry" role="listitem">
Pedregosa, Fabian, Gaël Varoquaux, Alexandre Gramfort, et al. 2011. <span>“Scikit-Learn: Machine Learning in <span>Python</span>.”</span> <em>Journal of Machine Learning Research</em> 12: 2825–30. <a href="https://jmlr.org/papers/v12/pedregosa11a.html">https://jmlr.org/papers/v12/pedregosa11a.html</a>.
</div>
<div id="ref-fna2025per" class="csl-entry" role="listitem">
U.S. Department of Agriculture, Food and Nutrition Administration. 2026. <em>Supplemental Nutrition Assistance Program Payment Error Rates, Fiscal Year 2025</em>. <a href="https://www.fns.usda.gov/snap/qc/per">https://www.fns.usda.gov/snap/qc/per</a>.
</div>
<div id="ref-fns310handbook" class="csl-entry" role="listitem">
U.S. Department of Agriculture, Food and Nutrition Service. 2023. <em>FNS Handbook 310: SNAP Quality Control Review Handbook</em>. <a href="https://www.fns.usda.gov/snap/fns-handbook-310">https://www.fns.usda.gov/snap/fns-handbook-310</a>.
</div>
<div id="ref-fns2024per" class="csl-entry" role="listitem">
U.S. Department of Agriculture, Food and Nutrition Service. 2025a. <em>Supplemental Nutrition Assistance Program Payment Error Rates, Fiscal Year 2024</em>. <a href="https://www.fns.usda.gov/snap/qc/per">https://www.fns.usda.gov/snap/qc/per</a>.
</div>
<div id="ref-fns2024techdoc" class="csl-entry" role="listitem">
U.S. Department of Agriculture, Food and Nutrition Service. 2025b. <em>Technical Documentation for the Fiscal Year 2024 Supplemental Nutrition Assistance Program Quality Control Database and the QC Minimodel</em>. <a href="https://snapqcdata.net/datafiles">https://snapqcdata.net/datafiles</a>.
</div>
<div id="ref-doj2019texas" class="csl-entry" role="listitem">
U.S. Department of Justice. 2019. <em>Texas <span class="nocase">Health and Human Services Commission</span> Agrees to Pay over $15 Million to Resolve <span>False Claims Act</span> Liability for Deficient <span>SNAP</span> Quality Control</em>. <a href="https://www.justice.gov/opa/pr/texas-health-and-human-services-commission-agrees-pay-over-15-million-resolve-false-claims">https://www.justice.gov/opa/pr/texas-health-and-human-services-commission-agrees-pay-over-15-million-resolve-false-claims</a>.
</div>
<div id="ref-doj2021snapqc" class="csl-entry" role="listitem">
U.S. Department of Justice. 2021. <em>False Claims Act Settlements Concerning Bias in SNAP Quality Control Processes (Virginia, Wisconsin, Alaska, Texas, Louisiana, Mississippi, Florida, Tennessee), Cumulative Recoveries Exceeding $67 Million</em>. <a href="https://www.justice.gov/archives/opa/pr/tennessee-department-human-services-agrees-pay-68-million-resolve-false-claims-act-liability">https://www.justice.gov/archives/opa/pr/tennessee-department-human-services-agrees-pay-68-million-resolve-false-claims-act-liability</a>.
</div>
<div id="ref-gao1984liability" class="csl-entry" role="listitem">
U.S. General Accounting Office. 1984. <em>Federal and State Liability for Inaccurate Payments of <span>Food Stamp</span>, <span>AFDC</span>, and <span>SSI</span> Program Benefits</em>. RCED-84-155. U.S. General Accounting Office. <a href="https://gao.justia.com/social-security-administration/1984/4/federal-and-state-liability-for-inaccurate-payments-of-food-stamp-afdc-and-ssi-program-benefits-rced-84-155">https://gao.justia.com/social-security-administration/1984/4/federal-and-state-liability-for-inaccurate-payments-of-food-stamp-afdc-and-ssi-program-benefits-rced-84-155</a>.
</div>
<div id="ref-gao2007errors" class="csl-entry" role="listitem">
U.S. Government Accountability Office. 2007. <em>Food <span>Stamp</span> <span>Program</span>: Payment Errors and Trafficking Have Declined Despite Increased Program Participation</em>. GAO-07-422T. U.S. Government Accountability Office. <a href="https://www.gao.gov/products/gao-07-422t">https://www.gao.gov/products/gao-07-422t</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>7 U.S.C. § 2013(a)(2)(B)(iii). The test applies mechanically to each year’s rate and is independent of the state’s election. The fiscal 2025 rates published in June 2026 settle the first leg: seven jurisdictions — Alaska (23.15%), the District of Columbia, Delaware, Georgia, Illinois, New Mexico, and Oregon — crossed on fiscal 2025 and owe nothing in FY2028, with no bill before FY2029 — keyed to the fiscal 2026 rate unless that rate also crosses, which pushes the start to FY2030 and is nearly certain for Alaska. Fiscal 2024 rates would have qualified ten, including New York (14.09%); New York’s fiscal 2025 rate of 13.18% misses the 13.33% threshold, so its delay now rides on the fiscal 2026 measurement. Any projection of FY2028 outlays must model the delay, and the simulator does: delayed years enter expected bills as zero.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The published thresholds — $48, $54, $56, $57, $58 for fiscal 2022–26 — are uniquely reproduced by flooring the indexed value, which puts the fiscal 2027 threshold at an estimated $59: $59.58 unrounded on the May 2026 Thrifty Food Plan cost of $1,018.20, with $60 requiring a June figure of at least $1,025.40. The estimate hardens when the June figure publishes.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>